
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example # root ユーザーパスワード
      MYSQL_DATABASE: graduationdb # データベース名
      MYSQL_USER: nkslong # ユーザー名
      MYSQL_PASSWORD: nkslong # ユーザーパスワード
    ports:
      - 3306:3306 # コンテナ外部からアクセス出来るようにする。