spring:
  datasource:
    url: "jdbc:mysql://localhost/graduationdb"
    username: "nkslong"
    password: "nkslong"
  sql:
    init:
        mode: always # SQLにデータを書けるようにする。
        encoding: UTF-8 # 文字フォントを変更する。

logging:
    level:
        root: info
    file:
        name: dl.log
    logback:
        rollingpolicy:
            max-file-size: 1MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true